BEGIN;

CREATE TABLE IF NOT EXISTS public.source_doc_passage (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id bigint NOT NULL REFERENCES public.story_series(id) ON DELETE CASCADE,
    source_doc_id uuid NOT NULL REFERENCES public.source_doc(id) ON DELETE CASCADE,
    chapter_id text,
    passage_no integer NOT NULL CHECK (passage_no > 0),
    start_offset integer NOT NULL CHECK (start_offset >= 0),
    end_offset integer NOT NULL CHECK (end_offset > start_offset),
    passage_text text NOT NULL,
    passage_text_sha256 text NOT NULL,
    source_doc_sha256 text NOT NULL,
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', passage_text)) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source_doc_id, passage_no),
    CHECK (char_length(passage_text) = end_offset - start_offset)
);

CREATE INDEX IF NOT EXISTS idx_source_doc_passage_story_order
    ON public.source_doc_passage (story_id, chapter_id, passage_no);

CREATE INDEX IF NOT EXISTS idx_source_doc_passage_search
    ON public.source_doc_passage USING gin (search_vector);

COMMIT;
