import os
import re
from worker_runtime_config import GLOBAL_LLM_COOL_OFF_SECONDS

# connection defaults
DEFAULT_DSN = "postgresql://novel:novelpass@localhost:5433/novel"
DEFAULT_LLM_BASE = os.getenv("LLM_API_BASE", "http://localhost:8080/v1")
DEFAULT_LLM_MODEL = os.getenv("LLM_MODEL", "qwen2.5-7b")
DEFAULT_LLM_API_KEY = os.getenv("LLM_API_KEY", "local")
DEFAULT_EMBED_BASE = os.getenv("LLM_EMBED_BASE", DEFAULT_LLM_BASE)
DEFAULT_EMBED_MODEL = os.getenv("LLM_EMBED_MODEL", "text-embedding-3-small")

# split configuration
SPLIT_MAX_CHARS = 25000
SPLIT_CHUNK_TARGET = 7600
SPLIT_CHUNK_OVERLAP = 320
SPLIT_MIN_GAP = 250
SPLIT_MIN_SCENE_CHARS = 260
SPLIT_MAX_LLM_CALLS_PER_CHAPTER = 5
SPLIT_LONG_CHAPTER_CHARS = 5000
SPLIT_PROFILE_GLOBAL_KEY = "__global__"
SPLIT_PROFILE_HISTORY_MAX = 30
SPLIT_STRATEGY_MAX_ESCALATIONS = 2
SPLIT_HARD_FAIL_MID_WORD_RATIO = 0.05
SPLIT_HARD_FAIL_MID_WORD_COUNT = 2
SPLIT_HARD_FAIL_SEMANTIC_COUNT = 1
SPLIT_HARD_FAIL_SEMANTIC_FLAGGED_PCT_GUARD = 20.0
SPLIT_HARD_FAIL_SEMANTIC_QUOTE_BREAK_GUARD = 1
SPLIT_BOUNDARY_SHIFT_WINDOW_CHARS = 220
SPLIT_OVERSIZED_SPLIT_WINDOW_CHARS = 420
SPLIT_MAX_OVERSIZED_DETERMINISTIC_SPLITS_PER_CHUNK = 2
SPLIT_DIALOGUE_ATTRIBUTION_GUARD_ENABLED = True
SPLIT_RECOVERY_RECURSION_MIN_BUDGET_SEC = 45.0
SPLIT_RECOVERY_REPAIR_MIN_BUDGET_SEC = 20.0
SPLIT_BUDGET_GUARD_ENABLED = True
SPLIT_BUDGET_GUARD_MIN_CHARS = 9000
SPLIT_ANCHOR_ENABLE = True
SPLIT_HARD_ANCHOR_TOLERANCE_CHARS = 200
SPLIT_ANCHOR_SNAP_WINDOW_CHARS = 180
SPLIT_ANCHOR_DEDUP_WINDOW_CHARS = 140
SPLIT_ANCHOR_MAX_PER_CHAPTER = 24
SPLIT_ANCHOR_CLEAN_START_WINDOW_CHARS = 220
SPLIT_ANCHOR_DIALOGUE_GUARD_ENABLED = True
SPLIT_FRAGMENT_SHORT_CHARS = 600
SPLIT_FRAGMENT_SCORE_RETRY_THRESHOLD = 62.0
SPLIT_FORCE_RETRY_FRAGMENTATION_THRESHOLD = 45.0
SPLIT_FORCE_RETRY_FRAGMENTATION_WITH_HINTS_THRESHOLD = 30.0
SPLIT_FORCE_RETRY_HINT_MIN = 0.55
SPLIT_EXPLORATION_RATE = 0.12
SPLIT_STRONG_HINT_THRESHOLD = 0.8

# profile learning
SPLIT_PROFILE_CHAPTER_MIN_BOUNDARIES = 50
SPLIT_PROFILE_CHAPTER_MIN_HARD_FLAGS = 5
SPLIT_PROFILE_CHAPTER_MIN_RUNS = 3
SPLIT_PROFILE_GLOBAL_LR = 0.2
SPLIT_PROFILE_CHAPTER_LR = 1.0

# S3 parameters used by semantic resplit
S3_MIN_CONFIDENCE = 0.62
S3_MAX_OFFSET_JUMP = 900
S3_MAX_REJECTED_JUMP_RATIO = 0.34
S3_MIN_PROOF_RATIO = 0.6

# memory enrich
MEMORY_ENRICH_ALGO_VERSION = "memory_v1"
MEMORY_ENRICH_MAX_RETRIES = 3

# patterns and helpers for splitting
ABBREV_PATTERN = re.compile(r"\b(?:Mr|Mrs|Ms|Dr|Prof|St)\.")
INITIAL_PATTERN = re.compile(r"\b[A-Z]\.")
NAME_HEAD_PATTERN = re.compile(r"^[A-Z][a-z]{1,24}\b")

BROKEN_WORD_SUFFIXES = {
    "ren",
    "ted",
    "ning",
    "tion",
    "tions",
    "ment",
    "ments",
    "less",
    "ness",
    "able",
    "ible",
    "ward",
    "wards",
}
