import { Client } from "pg";

const API_BASE = process.env.API_BASE || "http://localhost:3001";
const DB_DSN = process.env.DATABASE_URL || process.env.DB_DSN || "postgresql://novel:novelpass@localhost:5433/novel";
const STORY_SLUG = process.env.DOCTOR_STORY_SLUG || "doctor_tmp";

function randInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

async function post(path, body) {
  const res = await fetch(`${API_BASE}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok || json?.ok === false) {
    throw new Error(`${path} failed: ${res.status} ${JSON.stringify(json)}`);
  }
  return json;
}

async function main() {
  const chapter = randInt(80, 98);
  const idx = randInt(1, 9999);
  const workunit = `ch${chapter}_s${idx}`;
  console.log(`[doctor] story=${STORY_SLUG} workunit=${workunit}`);

  const client = new Client({ connectionString: DB_DSN });
  await client.connect();
  const defaultStoryRes = await client.query(`SELECT id FROM public.story_series WHERE slug = 'default' LIMIT 1`);
  const defaultStoryId = Number(defaultStoryRes.rows[0]?.id ?? 0);
  const beforeDefaultSceneCountRes = await client.query(
    `SELECT count(*)::int AS n FROM public.narrative_scene WHERE story_id = $1`,
    [defaultStoryId]
  );
  const beforeDefaultSceneCount = Number(beforeDefaultSceneCountRes.rows[0]?.n ?? 0);
  await client.end();

  const base = `/api/${STORY_SLUG}/scenes`;
  const intake = await post(`${base}/intake`, {
    workunit_id: workunit,
    title: `Doctor ${workunit}`,
    idea: "Doctor smoke test",
  });

  const outline = await post(`${base}/outline`, {
    scene_id: intake.scene_id,
    beats_json: { beats: ["A", "B", "C"] },
    text_content: "Outline text",
  });

  const draft = await post(`${base}/draft`, {
    scene_id: intake.scene_id,
    text_content: "Draft text generated by doctor.",
    summary: "doctor draft",
  });

  const evaluate1 = await post(`${base}/evaluate`, {
    scene_id: intake.scene_id,
    mode: "manual",
    eval_json: {
      rubric: { logic: 4, pacing: 4, consistency: 4, voice: 4 },
      overall: 4,
      issues: ["Need stronger midpoint turn."],
      suggestions: ["Tighten scene ending."],
      meta: { model: "manual", prompt_rev: "eval_v1", ts: new Date().toISOString() },
    },
  });

  const rewrite = await post(`${base}/rewrite`, {
    scene_id: intake.scene_id,
    mode: "llm",
    summary: "doctor rewrite llm",
  });

  const evaluate2 = await post(`${base}/evaluate`, {
    scene_id: intake.scene_id,
    mode: "llm",
    llm_params: { model: "stub", prompt_rev: "eval_v1" },
  });

  const lock = await post(`${base}/lock`, { scene_id: intake.scene_id });

  const verify = new Client({ connectionString: DB_DSN });
  await verify.connect();
  const storyRes = await verify.query(`SELECT id, slug FROM public.story_series WHERE slug = $1 LIMIT 1`, [STORY_SLUG]);
  if (!storyRes.rows[0]) throw new Error(`story not found: ${STORY_SLUG}`);
  const storyId = Number(storyRes.rows[0].id);

  const latest = await verify.query(
    `SELECT id, story_id, status, current_kind, current_version_no
     FROM public.narrative_scene_latest
     WHERE id = $1`,
    [intake.scene_id]
  );
  const runDetail = await verify.query(
    `SELECT step, input_json, output_json
     FROM public.narrative_pipeline_run
     WHERE scene_id = $1
       AND step IN ('draft', 'rewrite')
       AND status = 'OK'
     ORDER BY id ASC`,
    [intake.scene_id]
  );
  const versionText = await verify.query(
    `SELECT text_content
     FROM public.narrative_scene_version
     WHERE scene_id = $1 AND kind = 'rewrite'
     ORDER BY version_no DESC
     LIMIT 1`,
    [intake.scene_id]
  );
  const runs = await verify.query(
    `SELECT step, status, count(*)::int AS n
     FROM public.narrative_pipeline_run
     WHERE scene_id = $1
     GROUP BY step, status
     ORDER BY step, status`,
    [intake.scene_id]
  );
  const runStoryMismatch = await verify.query(
    `SELECT count(*)::int AS n
     FROM public.narrative_pipeline_run
     WHERE scene_id = $1
       AND story_id <> $2`,
    [intake.scene_id, storyId]
  );
  const afterDefaultSceneCountRes = await verify.query(
    `SELECT count(*)::int AS n
     FROM public.narrative_scene
     WHERE story_id = $1`,
    [defaultStoryId]
  );
  await verify.end();

  if (!latest.rows[0]) throw new Error("scene not found in narrative_scene_latest");
  if (Number(latest.rows[0].story_id) !== storyId) throw new Error("scene story mismatch");
  if (latest.rows[0].status !== "LOCKED") throw new Error(`expected LOCKED but got ${latest.rows[0].status}`);
  if (Number(runStoryMismatch.rows[0]?.n ?? 0) !== 0) throw new Error("pipeline_run story_id mismatch");
  const draftRun = runDetail.rows.find((r) => r.step === "draft");
  const rewriteRun = runDetail.rows.find((r) => r.step === "rewrite");
  if (!draftRun?.input_json?.guard_stats) throw new Error("draft run missing guard_stats");
  if (!rewriteRun?.input_json?.guard_stats) throw new Error("rewrite run missing guard_stats");
  if (typeof versionText.rows[0]?.text_content !== "string") throw new Error("rewrite version text missing");
  if (!versionText.rows[0].text_content.includes("[CANON_GUARD]")) throw new Error("rewrite llm missing guard block");
  if (!versionText.rows[0].text_content.includes("[TODO: Question]")) throw new Error("rewrite llm missing TODO fallback");
  const afterDefaultSceneCount = Number(afterDefaultSceneCountRes.rows[0]?.n ?? 0);
  if (afterDefaultSceneCount !== beforeDefaultSceneCount) {
    throw new Error(
      `default story scene count changed: before=${beforeDefaultSceneCount} after=${afterDefaultSceneCount}`
    );
  }

  console.log("[doctor] intake:", intake);
  console.log("[doctor] outline:", outline);
  console.log("[doctor] draft:", draft);
  console.log("[doctor] evaluate1:", evaluate1);
  console.log("[doctor] rewrite:", rewrite);
  console.log("[doctor] evaluate2:", evaluate2);
  console.log("[doctor] lock:", lock);
  console.log("[doctor] latest:", latest.rows[0]);
  console.log("[doctor] runs:", runs.rows);
  console.log("[doctor] PASS");
}

main().catch((err) => {
  console.error("[doctor] FAIL", err);
  process.exit(1);
});
